baseURL: https://https://whoissuspicious.netlify.app/
title: Home
theme: bigspring-hugo-startup-theme
paginate: '3'
summaryLength: '15'
disqusShortname: ''
googleAnalytics: ''
markup:
  goldmark:
    renderer:
      unsafe: yes
